services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gearquest

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-4000}:4000"
    depends_on:
      - db
    networks:
      - gearquest
    environment:
      PORT: ${PORT:-4000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://gearquest:gearquest@db:5432/gearquest?schema=public}
      JWT_SECRET: ${JWT_SECRET:-supersecretjwt}
      CLIENT_ORIGIN: ${CLIENT_ORIGIN:-*}
      EMAIL_VERIFICATION_EXPIRATION_HOURS: ${EMAIL_VERIFICATION_EXPIRATION_HOURS:-24}
      APP_BASE_URL: ${APP_BASE_URL:-http://localhost:8080}
volumes:
  postgres_data:

networks:
  gearquest:
    driver: bridge


